<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Contacts</RootNamespace>
    <AssemblyName>Contacts</AssemblyName>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="contacts_icon.ico" />
    <Resource Include="Controls\photo_placeholder.png" />
    <Resource Include="photo_placeholder.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="View\App.xaml.cs" />
    <Compile Remove="View\MainWindow.xaml.cs" />
    <Compile Remove="View\obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs" />
    <Compile Remove="View\obj\Debug\App.g.cs" />
    <Compile Remove="View\obj\Debug\MainWindow.g.cs" />
    <Compile Remove="View\obj\Release\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs" />
    <Compile Remove="View\obj\Release\App.g.cs" />
    <Compile Remove="View\obj\Release\MainWindow.g.cs" />
    <Compile Remove="View\Properties\AssemblyInfo.cs" />
    <Compile Remove="View\Properties\Resources.Designer.cs" />
    <Compile Remove="View\Properties\Settings.Designer.cs" />
    <EmbeddedResource Remove="View\Properties\Resources.resx" />
    <None Remove="Controls\photo_placeholder.png" />
    <None Remove="photo_placeholder.png" />
    <Page Remove="View\App.xaml" />
    <Page Remove="View\MainWindow.xaml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="Contacts.ViewModel\ViewModel.csproj" />
  </ItemGroup>
</Project>